name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@V5

    - name: Run a multi-line script
      run: |
        #!/usr/bin/pwsh
        wget -O modules-raw.json https://github.com/Magisk-Modules-Alt-Repo/json/raw/refs/heads/main/modules.json
        $content = Get-Content modules-raw.json $content -replace "https://raw.githubusercontent.com/", "https://ghproxy.net/raw.githubusercontent.com/" -replace "https://github.com/", "https://ghproxy.net/github.com/"  | Set-Content modules.json
